server:
  port: ${SERVER_PORT:8888}

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPO_URI}
          default-label: ${GIT_BRANCH:main}
          clone-on-start: true
          username: ${GIT_USERNAME}
          password: ${GITHUB_TOKEN}
